#+TITLE:  Lecture à l'écran : défis du lecteur branché
		   
     Appareils mobiles et connectés → nouvelles formes de lectures et d'apprentissage.  A la lecture ''profonde'' du texte imprimé s'oppose la lecture ''de surface'' associée à l'hypertexte. ( =NP= en sous jacent les différents types de lectures;  peut-on y voir un rapport avec les besoins en lectures rapides (df Richaudeau) ou HTRB (à chercher?)).

     - Partie sur les liseuses.
       Les mécanismes de lecture à l'écran diffèrent de ceux mis en application lors d'une lecture d'un imprimé.   Cette nouvelle lecture appelle de nouvelles compétences.  En particulier, l'attention est mise à l'épreuve et peut entraîner des désagréments physiques.  Dans tous les cas, il y a bouleversement des habitudes du lecteur ''classique''.  Ces compétences sont acquises quand elles sont automatisées, ce qui demande une phase d'apprentissage et un entrainement/pratique régulier.
       Dans un hypertexte, le lecteur doit construire son chemin de lecture.  De plus, le texte défile à la différence du texte fixe de l'imprimé.  La lecture à l'écran semble plus fatigante pour les yeux.  Il est conseillé une période de repos de 15' après 2h de travail sur écran et de 10' par heure de travail intensif.  Les liseuses, utilisant l'encre électronique semblent moins fatigantes (pas de rétroéclairage de l'écran ; effet du rafraîchissement de l'écran).  Les systèmes de lecture à l'écran offrent des fonctions supplémentaires (agrandissement), contrôle plus grand de la lecture, recherches possibles, document enrichi de ressources multimédia, possibilité de commenter ou de lire les commentaires des lecteurs. (=NP= peut-on parler d'intégration de ressources quand le lien vers une vidéo fait ''sauter'' à la page du service de vidéo -- par exemple youtube -- faire des tests d'une telle intégration, comment la rendre propre si ce n'est pas le cas -- digression par parasitage --).  
     - Partie Enseignement
       Les nouvelles plate-formes de lecture offrent des nouveaux supports pour l'école. (=NP= n'est-il pas restrictif de voir ces outils uniquement comme des supports?).  Le terme ''lire'' n'est plus uniquement associé au support livre imprimé et textuel, mais intègre un univers ou l'image, le son et l'écrit coexistent.  On pourrait parler de ''translittératie'' (habilité à lire, écrire et interagir avec une variété de plate-formes.  De plus, de nouvelles compétences sociales sont mises en jeu et la possibilité d'utiliser le support en mobilité permet de novelles applications.  (=NP= que de nouvelles...).  L'enseignant doit mettre en place des conditions de l'appropriation du savoir.  Le mode d'organisation des documents se trouve modifié par rapport à l'imprimé.  Il conviendrai de faire autre chose de l'utilisateur d'Internet que celui de consommateur de contenu.  Collecte d'information: formuler des requêtes; distinguer les différents résultats (crédibilité, source, contenu a priori -- savoir mettre du sens sur l'information que l'on manipule).  Il est important de maintenir son intention en tête lors d'une recherche, pour éviter éparpillement.
       Il est tout aussi important de connaître les fonctionnalités du navigateur.  Savoir reformuler une requête en utilisant les résultats précédents.  Savoir utiliser les blogs et forum plutôt que de se contenter d'un moteur de recherche.  Distinguer les différents types de textes (opinion, information);  savoir vérifier la fréquence de mise à jour des sites, la qualité des liens, la qualité des inforamtiosn et indentifier le responsable du site.  Savoir repérer les sources crédibles et la clientèle ciblée par le site.  Savoir créer des passerelles et liens entre l'information présentée et ses connaissances antérieures.  
     - Apprentissage et plates-formes mobiles
       Désigné mar *m-learnig*.  L'article n'est pas forcément très pertinent sur ce point.  En effet, il expose une vision dans laquelle il y a multiplication de plates-formes dédiées, ne faudrait-il pas plus disposer de plates-formes de rédaction/publication, de plates-formes de lecture, des plates-formes de commentaires, ...
     - Le livre numérique
       Chronique d'une mort annoncée qui ne c'est pas encore produite.  La première liseuse date de 1998.  La disponibilité des livres est cependant réélle depuis 2006-2007.  2009 liseuse (400$).  2012?  L'iPad change la donne en 2010, offrant un appareil plus polyvalant (+tactile et couleur).  Le livre électronique permettant de consulter des documents multimédia n'existe pas encore (à l'exception de l'iPad).
