#+TITLE: Sur ''lire et rédiger a la fac'' {BMMq 374.11 BOEG} edition 2005
   :PROPERTIES:
   :ID:       ca40730c-fd1b-4032-a0e4-58b93957824d
   :END:
   Révisé en 2010 ("le guide des méthodes de travail de l'étudiant"])

   Lieu de travail : 
   - agréable, 
   - clair (luminosité lumière arrivant de gauche)
   - meubles de rangement
   - correspondant à ses besoins

   - aération du lieu (pdt pauses)
   - prévoir phases de travail non assis (oxygénation du cerveau)

   Ordinateur: 
   - éviter écran à contre jour
   - écran en face du corps
   - distance tête écran 50 cm
   -  libérer espace sur table pour activités hors informatique
   -  place du clavier
   - pauses / 30 minutes

   La position assise n'est pas naturelle pour le corps (effort engendré).

   Il est important de découvrir ses besoins.

   Différents types de mémoires :
   - visuelle
   - auditive
   - kinesthésique (gestes)
   Toutes présentes mais une peut prédominer.

   Planifier un travail de recherche :
   => PREPARATION et PLAN (1 sem/12)
   => RECHERCHE DOC (4,5 sem/12)
   => EVALUATION TRI (5 sem/12)
   => LECTURES/NOTES/JOURNAL (6/12)

   - recherche bibliographique
   - évaluation
   - lecture (+prise de notes et journal de bord)
   PEUVENT ETRE MENEES EN //

   => PREPARATION DE LA REDACTION
   - Rédaction
     - Premier jet (1/3 sem x 4)
     - Construction du texte (mise au point) (2/3 x 4)
     - correction stylistique (3/4 sem)
     - corrections techniques et mise en page (1/2 sem)
     - diffusion (1/2 sem)
   LIMITER NOUVELLES RECHERCHES ET LECTURES
   POUR UN TRAVAIL LONG DECOUPER EN PHASES AVEC 3 PARTIES PRECEDENTES (la correction stylistique peut être faite en dernier)

   Plages de travail 40/50' suivi de 5'/10' de pause.
   Pause=distraction (rupture monotonie/activité complètement différente)

   Journal de bord comme outil d'apprentissage
   Ecrire=noter ce que l'on sait mais aussi d'actualiser les connaissances enfouies, relier les idées et de faire émerger nouvelles. Rend la pensée visible et laisse des traces.
   Il est alors de possible de réexaminer, améliorer, réordronner, préciser.

   Conseiller d'écrire régulièrement (idées, questions, étonnements,...) dans un journal  de bord.
   Possible d'utiliser des couleurs différentes , utiliser schémas, dessis, courbes, symboles,...
   Le carnet doit être à portée de main.

   - points obscurs
   - idées au vol
   - observations
   - réfléexion
   - compte rendu conversation
   - esquisses de plan , projets de titre, esquisses d'introduction ou conclusion, ébauches, bilans hebdo


   La pensée passe d'un langage interne (à soi -subjectif-) à un langage externe (pour les autres -strict-)

   Prise de note optimisée :
   1 semaine 50% info perdue
   2 semaines 80% infos perdues

   ->QUI? QUOI? QUAND? OU? COMMENT? POURQUOI? POUR QUOI? COMBIEN?
   ->Extraire structure 
   --> questions, commentaires en marge (mais pas visibles directement, perturbe attention).

   Ne pas TOUT noter.
   Préparer la prise de note.
   Fin de prise de note, récapituler rapidement.,

   Extraire : mots clefs, completer trous, réécrire ce qui est illisible, ce qui est abrégé, chercher significations mots nouveaux ou obscurs, corriger l'ortho; trouver exemples personnels ; noter textes ou auteurs qu'évoque le sujet  ; noter questions et chercher réponses; noter ce qui est obscur., souligner encadrer colorer, mettre en schéma le texte.

   Supprimer mots inutiles, utiliser abréviations  et ou symboles., langue SMS

   Reprendre les notes dans la journée ou le lendemain au max=> mise au propre et relecture.

   Type de notes :
   - par catégories et 
   - méthode Cornell (informations liées par bloc de 3 ->associer après à un mot clef)
   - avec structuration hiérarchique pdt la prise de notes

   Méthode de mémorisation : Sebastian Leitner

   Intégration des outils mnémotechniques / intération informatique (virtualisation des associations ?)

   FIN p 70 (Voir CHAP2)

Révisé en 2010 ("le guide des méthodes de travail de l'étudiant"])

Lieu de travail : 
- agréable, 
- clair (luminosité lumière arrivant de gauche)
- meubles de rangement
- correspondant à ses besoins

- aération du lieu (pdt pauses)
- prévoir phases de travail non assis (oxygénation du cerveau)

Ordinateur: 
- éviter écran à contre jour
- écran en face du corps
- distance tête écran 50 cm
-  libérer espace sur table pour activités hors informatique
-  place du clavier
- pauses / 30 minutes

La position assise n'est pas naturelle pour le corps (effort engendré).

Il est important de découvrir ses besoins.

Différents types de mémoires :
- visuelle
- auditive
- kinesthésique (gestes)
Toutes présentes mais une peut prédominer.

Planifier un travail de recherche :
=> PREPARATION et PLAN (1 sem/12)
=> RECHERCHE DOC (4,5 sem/12)
=> EVALUATION TRI (5 sem/12)
=> LECTURES/NOTES/JOURNAL (6/12)

- recherche bibliographique
- évaluation
- lecture (+prise de notes et journal de bord)
PEUVENT ETRE MENEES EN //

=> PREPARATION DE LA REDACTION
- Rédaction
  - Premier jet (1/3 sem x 4)
  - Construction du texte (mise au point) (2/3 x 4)
  - correction stylistique (3/4 sem)
  - corrections techniques et mise en page (1/2 sem)
  - diffusion (1/2 sem)
LIMITER NOUVELLES RECHERCHES ET LECTURES
POUR UN TRAVAIL LONG DECOUPER EN PHASES AVEC 3 PARTIES PRECEDENTES (la correction stylistique peut être faite en dernier)

Plages de travail 40/50' suivi de 5'/10' de pause.
Pause=distraction (rupture monotonie/activité complètement différente)

Journal de bord comme outil d'apprentissage
Ecrire=noter ce que l'on sait mais aussi d'actualiser les connaissances enfouies, relier les idées et de faire émerger nouvelles. Rend la pensée visible et laisse des traces.
Il est alors de possible de réexaminer, améliorer, réordronner, préciser.

Conseiller d'écrire régulièrement (idées, questions, étonnements,...) dans un journal  de bord.
Possible d'utiliser des couleurs différentes , utiliser schémas, dessis, courbes, symboles,...
Le carnet doit être à portée de main.

- points obscurs
- idées au vol
- observations
- réfléexion
- compte rendu conversation
- esquisses de plan , projets de titre, esquisses d'introduction ou conclusion, ébauches, bilans hebdo


La pensée passe d'un langage interne (à soi -subjectif-) à un langage externe (pour les autres -strict-)

Prise de note optimisée :
1 semaine 50% info perdue
2 semaines 80% infos perdues

->QUI? QUOI? QUAND? OU? COMMENT? POURQUOI? POUR QUOI? COMBIEN?
->Extraire structure 
--> questions, commentaires en marge (mais pas visibles directement, perturbe attention).

Ne pas TOUT noter.
Préparer la prise de note.
Fin de prise de note, récapituler rapidement.,

Extraire : mots clefs, completer trous, réécrire ce qui est illisible, ce qui est abrégé, chercher significations mots nouveaux ou obscurs, corriger l'ortho; trouver exemples personnels ; noter textes ou auteurs qu'évoque le sujet  ; noter questions et chercher réponses; noter ce qui est obscur., souligner encadrer colorer, mettre en schéma le texte.

Supprimer mots inutiles, utiliser abréviations  et ou symboles., langue SMS

Reprendre les notes dans la journée ou le lendemain au max=> mise au propre et relecture.

Type de notes :
- par catégories et 
- méthode Cornell (informations liées par bloc de 3 ->associer après à un mot clef)
- avec structuration hiérarchique pdt la prise de notes

Méthode de mémorisation : Sebastian Leitner

Intégration des outils mnémotechniques / intération informatique (virtualisation des associations ?)

----> FIN p 70 (Voir CHAP2)
** FAIRE [#B] Techniques de lecture rapide (Exercices)
   SCHEDULED: <2015-01-13 mar.>
   :PROPERTIES:
   :ID:       41ffed89-660f-4ac0-8db0-2679baf6c698
   :END:
** FAIRE [#B] Voir méthodes de prises de notes proposées
   SCHEDULED: <2015-01-13 mar.>
   :PROPERTIES:
   :ID:       521f4677-7384-4d39-96cb-00b0259714f4
   :END:
** FAIRE [#A] Sur Partie 1
   SCHEDULED: <2015-02-02 lun.>
   :LOGBOOK:
   - State "ANNULÉ"     from "FAIT"       [2014-10-06 lun. 17:04]
   :END:
   :PROPERTIES:
   :ID:       e5696da9-b62e-4598-b958-387dfdcaa301
   :END:
*** p3-12 == L'information sous le prisme du numérique ==
  S'interroge sur la place de la notion d'information dans un univers numérisé.  La matière première du numérique étant l'information.
  - dans le monde numérique, tout est information.  Mais il faut garder à l'esprit que l'information numérique est pour une grande part une information *numérisée*.
  - Réflexion sur les problèmes posés sur la qualité, fiabilité, accessibilité et capillarité de l'information ''quotidienne''.  Le traitement grand public de l'information insiste sur les registres des peurs et scandales.
  - notion de ''pic informationnel'' sur un sujet donné ou durant une période donnée.  Un pic chasse l'autre.
  - notion de ''bien public informationnel'' (quel lien avec les données ouvertes).
  - référence d'intérêt : 
    - Blatz C., interconnexion entre la culture humaniste et la culture informationnelle (2012) http://www.andep.org & http://ardeplr.fr
    - Doueihi M., Pour un humanisme numérique, 2011
  - Corpus d'articles du ''Monde'' donné en annexe (p12)

*** [#B] p13-26 == Infobésité == *REPRENDRE* 			  :reprendre:
     DEADLINE: <2015-01-31 sam.>
     :PROPERTIES:
     :ID:       377bf4bf-d4c5-4abb-9231-a86c73c631c7
     :END:
  - historiquement : quantité d'information est une bonne chose.
  - en ce sens, les premiers moteurs de recherche ont apporté un bénéfice important.
  - cependant, ces bénéfices se sont dégradés depuis leur apparition.
  - l'accroissement massif et constant du nombre d'informations disponible implique que s'interroger sur leur construction, sur association et leur traitement.
  - quelle organisation des informations sur Internet?
  - de plus la qualité des informations disponibles semble décroitre en fonction de leur quantité.
  - ceci engendre une perte de temps dans le traitement des flux d'informations (sous divers forme : réunions, recherche d'infos, mels,...) : surcharge informationnelle.
  - 
  - référence : blair, reading strategies for coping with information overload. (journal of the history of ideas).

-----> P 27
** FAIRE [#B] ----> Chapitre IV
   SCHEDULED: <2015-01-13 mar.>
   :PROPERTIES:
   :ID:       6bbcb409-49be-47c5-a355-ee8fbcafc8d6
   :END:


